// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfC5VoKmcPGEnmz_97AkiMmpF2dL_SJo4',
    appId: '1:599471873355:web:12d8f622246bbe7f449cce',
    messagingSenderId: '599471873355',
    projectId: 'cmsapp-fb3d1',
    authDomain: 'cmsapp-fb3d1.firebaseapp.com',
    storageBucket: 'cmsapp-fb3d1.appspot.com',
    measurementId: 'G-X9XX2KGEE5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDACzSk6tDedWoHl_9PJxB1_yaa8ivFsME',
    appId: '1:599471873355:android:e7623d59d640da53449cce',
    messagingSenderId: '599471873355',
    projectId: 'cmsapp-fb3d1',
    storageBucket: 'cmsapp-fb3d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3bgHsPsFRJj_ecmpqb2EDAouJfrMDGPw',
    appId: '1:599471873355:ios:5c1fa961d0e01ca8449cce',
    messagingSenderId: '599471873355',
    projectId: 'cmsapp-fb3d1',
    storageBucket: 'cmsapp-fb3d1.appspot.com',
    iosBundleId: 'com.example.cmsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3bgHsPsFRJj_ecmpqb2EDAouJfrMDGPw',
    appId: '1:599471873355:ios:5c1fa961d0e01ca8449cce',
    messagingSenderId: '599471873355',
    projectId: 'cmsapp-fb3d1',
    storageBucket: 'cmsapp-fb3d1.appspot.com',
    iosBundleId: 'com.example.cmsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfC5VoKmcPGEnmz_97AkiMmpF2dL_SJo4',
    appId: '1:599471873355:web:3f636379838f4929449cce',
    messagingSenderId: '599471873355',
    projectId: 'cmsapp-fb3d1',
    authDomain: 'cmsapp-fb3d1.firebaseapp.com',
    storageBucket: 'cmsapp-fb3d1.appspot.com',
    measurementId: 'G-ZTHM579QVH',
  );
}
